apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
      - image: blacknikka/fluent-client:0.1
        imagePullPolicy: Always
        name: fluentd
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        # securityContext:
        #   privileged: true
        #   readOnlyRootFilesystem: true
    #   securityContext:
    #     privileged: true
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 2000
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
