apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server-deployment
spec:
  selector:
    matchLabels:
      app: redis-server
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      containers:
      - name: random-go
        image: blacknikka/redis-server:0.1
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
