apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-app-deployment
spec:
  selector:
    matchLabels:
      app: random-go
  replicas: 2
  template:
    metadata:
      labels:
        app: random-go
    spec:
      containers:
      - name: random-go
        image: blacknikka/go-k8s:0.1
        imagePullPolicy: Always
        volumeMounts:
        - name: go-src-volume
          mountPath: /go/src/github.com/blacknikka/go-k8s
        command: ["bash", "-c"]
        args:
        - |
          rm -rf ./docker && \
          rm -rf ./k8s && \
          mv ./src/* ./ && \
          rm -rf ./src && \
          go run main.go
        resources:
          limits:
            cpu: 200m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
      initContainers:
      - name: init
        image: blacknikka/src-cloner:0.1
        imagePullPolicy: Always
        env:
        - name: CONTENTS_SOURCE_URL
          value: "https://github.com/blacknikka/go-k8s.git"
        volumeMounts:
        - name: go-src-volume
          mountPath: /src/go-k8s
      volumes:
      - name: go-src-volume
        emptyDir: {}