apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-normal
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: normal
  hostPath:
    path: /blacknikka/k8s/src
    type: DirectoryOrCreate
