apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-normal-claim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: normal
